model: comusion
enabled: true
save_eval_samples: true
train:
  epochs: 300
  early_stopping:
    enabled: true
    patience: 15
    min_delta: 0.0001
    warmup: 5
    monitor: train_loss
defaults:
  model_type: CoMusion
  dtype: float32
  remove_model_internals: false
  model_specs:
    node_n: 63
    act: nn.Tanh
    dct_dim: 100
    gcn_dim: 128
    gcn_drop: 0.5
    inner_stage: 2
    outer_stage: 3
    trans_dim: 256
    trans_drop: 0.1
    trans_ff_dim: 256
    trans_num_heads: 4
    trans_num_layers: 4
  data_specs:
    augmentation: 0
    data_aug: false
    rota_prob: 0
    multimodal_threshold: 0.5
    humanmac_multimodal_threshold: 0.5
  diff_specs:
    beta_schedule: ours
    diffuse_steps: 10
    div_k: 2
    loss_type: l1
    objective: pred_x0
  learn_specs:
    batch_size: 256
    num_epoch_fix_lr: 200
    sched_policy: lambda
    train_epoch: 300
    train_lr: 0.0001
    weight_decay: 0
  loss_weight_specs:
    history_weight: 1
    future_weight: 1
  st_loss_specs:
    loss_weight_scale: 10
  logging_specs: {}
